name: Continuous Deployment

on:
  push:
    branches: [ main ]   # deploy automatically after merge
  workflow_dispatch:     # manual trigger using run CD workflow under Actions
  schedule:
    #- cron: "50 16 * * *"   # every day at 10 pm ist
    - cron: "*/5 * * * *"   # every 5 minutes


jobs:
  deploy:
    runs-on: ubuntu-latest   # use your local runner if you want local deployment
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change to your region

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform
