name: Continuous Integration test
on:
  pull_request:
    branches: [ main ]  # Runs when a PR targets main
  push:
    branches: [ main ] # Runs when you push directly to main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Formatting
        run: terraform fmt -check

      - name: Validate Terraform
        run: terraform validate

      - name: Initialize Terraform
        run: terraform init -backend=false # initializes providers without connecting to a remote backend (faster, safer in CI)

      #- name: Preview Infrastructure Changes
      #  run: terraform plan -no-color -input=false
